- name: My first play
  hosts: homelab
  vars_files:
    - secret
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

   - name: Ensure docker is the latest version
     become: true
     ansible.builtin.apt:
      name: docker.io
      state: latest

