version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: /home/ansible/nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
      - /home/ansible/nginx/logs:/etc/nginx/logs
    restart: always
